### PR TITLE
one lign update and git

### PR DESCRIPTION
**Pull request by Daebis**

### CODE REVIEW

**Comment by nirenjan** [comment]
This is not something that I think should be in the official repository - the instructions that you've added appear to be specific to your use case, and it is not general.

Also, the addition of `git` to the dependency list does not make sense. The dependency list is just that - the list of packages necessary to build (and possibly test) this source code. There is no dependency on `git` within the sources, except for the line you have added. It should be obvious that anybody who has a copy of the source code already has git installed, or they have obtained the sources from a source tarball, which does not need git.

Therefore, I am rejecting and closing this pull request.

**Comment by Daebis** [comment]
git package are necesary to "sudo git clone" commande
my usage aren't secifi, i'm just a ubuntu user 
and, it's good to be friendly user evry user aren't git's expert

**Comment by nirenjan** [comment]
A better place for this might be in the discussions section. It is my opinion that the instructions are sufficient to a user with moderate technical skills, which is for whom this repository is targeted.

A bit of unsolicited advice regarding your changes though - the only command that needs `sudo` is the `make install` step, the rest of them can be run as the unprivileged user. You appear to add `sudo` for everything because you have copied the code into `/opt`, which may not be writable by the unprivileged user. In general, the instructions for most open source software (not just this one) require that you clone the sources to somewhere where you have write permissions, typically your home directory, build the code as yourself, then only use `sudo` for the final `make install` step.

**Comment by Daebis** [comment]
indeed I could have used the discussion section, I hadn't noticed it.

considered that the set of users who arrive here at your technical level is an error. an error which amplifies the idea that Gnu_linux and for example ubuntu is addressed only to experts in linux.

which is obviously wrong, we must think of the average user with vague knowledge.
I am the very example of it, I install in / opt because I was taught like that, since you do not specify it in your installation instructions.

when you search on google "ubuntu x52 hotas" you arrive on your project page. It is therefore normally that beginners arrive here, please keep this in mind

either by improving your instruction from a beginner's point of view,
or by giving the link of the graphic project, as you did here, but directly on the main page.

**Comment by nirenjan** [comment]
You make some very good points. I will take them under consideration.

**Comment by Daebis** [comment]
have a good day
and thanks you for you soft even if it only works in command line.

**Pull request closed without merging**
